theme: jekyll-theme-slate
title: "Pyongsan's Portfolio"
description: "フリーランス SE/PG | Webシステム開発 | 業務システム開発 | リーダー | マネジメント"

# 基本情報
url: "https://pyongsanmichelle.github.io/"
github_username: pyongsanmichelle
email: pyongsan.michelle@gmail.com

# 表示設定
show_downloads: false

